INSERT INTO category (parent_id, name, keywords, description) VALUES
	("0", "Sportswear", "", ""),
	("0", "Mens", "", ""),
	("0", "Womens", "", ""),
	("1", "Nike", "", ""),
	("1", "Under Armour", "", ""),
	("1", "Adidas", "", ""),
	("1", "Puma", "", ""),
	("1", "ASICS", "", ""),
	("2", "Fendi", "", ""),
	("2", "Guess", "", ""),
	("2", "Valentino", "", ""),
	("2", "Dior", "", ""),
	("2", "Versace", "", ""),
	("2", "Armani", "", ""),
	("2", "Prada", "", ""),
	("2", "Dolce and Gabbana", "", ""),
	("2", "Chanel", "", ""),
	("2", "Gucci", "", ""),
	("3", "Fendi", "", ""),
	("3", "Guess", "", ""),
	("3", "Valentino", "", ""),
	("3", "Dior", "", ""),
	("3", "Versace", "", ""),
	("0", "Kids", "", ""),
	("0", "Fashion", "", ""),
	("0", "Household", "", ""),
	("0", "Interiros", "", ""),
	("0", "Clothing", "", ""),
	("0", "Bags", "Сумки ключевики", "Сумки описание"),
	("0", "Shoes", "", "")

INSERT INTO product (
    category_id,
    name,
    content,
    price,
    img,
    hit,
    new,
    sale)
    VALUES
        ("4", "Джинсы Garcia 244/32/856 28-32 р Серо-синие", "Великолепные джинсы", "10", "product1.jpg", "0", "0", "0"),
        ("4", "Джинсы MR520 MR 227 20002 0115 29-34 р Синие", "Амбициозные джинсы", "56", "product2.jpg", "1", "0", "0"),
        ("9", "Блуза Tom Tailor TT 20312490071", "Испанский ночной бренд", "20", "product3.jpg", "1", "1", "0"),
        ("21", "Блуза Mango 53001245", "Ведущий бренд", "70", "product4.jpg", "1", "0", "1"),
        ("25", "Блузка Kira Plastina 17-16-17456>", "Простые джинсы", "0", "product5.jpg", "1", "0", "0"),
        ("26", "Кардиган Lavi's Icy", "Просто джинсики", "100", "product6.jpg", "1", "0", "0")